### ISSUE TITLE
Pressure keyword

### ISSUE THREAD

**Issue by liviabp** [libAtoms/pymatnext#1]
We should have a keyword to set the pressure for the simulation (I think the default is 0.0?)

**Comment by bernstei** [comment]
There _is_ a keyword, but it's not supported with LAMMPS propagation. It'll be easy to add.  Where do you think an exhaustive list of parameters and default values belong?  The READMEs just have a reasonable example, not every single param.

**Comment by liviabp** [comment]
Maybe as in pymatnest, and have these in one of the python files between the triple quotes? So when a documentation is generated these are all listed.

**Comment by bernstei** [comment]
Pressure field is there (in GPa or native energy/volume units), and listed in the new documentation markdown.  I suspect there might be a bug having to do with the way the code checks for consistency with the expected param file format when it's actually used - it could use better testing.

Should work with ASE Calculators, but still no functionality within the LAMMPS fix, so I'll work on that soon.

**Comment by bernstei** [comment]
LAMMPS implementation is coming along.  I need to test it, but I don't anticipate any serious problems.
