### ISSUE TITLE
cell aspect ratio

### ISSUE THREAD

**Issue by liviabp** [libAtoms/pymatnext#2]
The aspect ratio change of the simulation cell should be limited - what's being done currently? This should probably be a keyword as well, maybe with a sensible default as 0.8?

**Comment by bernstei** [comment]
Supported as `configs.walk.cell.min_aspect_ratio`, just not documented.  As I asked in the pressure control issue, where do you think this belongs?

**Comment by liviabp** [comment]
yes, this is good!
